# 3.11 ハッシュ生成の関数

name: Hash functions

on: push

jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${HASH}"
        env:
            HASH: ${{ hashFiles('.github/workflows/3.11_hash-functions.yml')}}
