# 3.9 文字列生成の関数

name: Generate function

on: push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hi', 'world') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url, ',') }}
